
#' @title Generates a Questionnaire for Rshiny
#' @description
#'  Saves the pre-processed and merged Stroop deadline .csv data file into
#'  a specified directory, under a chosen file name.
#'
#' @param i The absolute filepath of the folder in which you want the file to be saved.
#'               Make sure you use a character string (e.g., "C:/...")
#' @returns A Questionnaire with Radio buttons in shiny
#' @details Use on data generated by JsPsych Stroop Deadline experiment.
#'
#' @note Requires your dataframe to already be in your Environment.
#' You can run merge_data_files() if you do not have your dataframe ready.
#'
#' @examples
#' data_folder <- getwd()
#' merge_data_files(data_folder)
#' save_data(data_folder, "my_data")
#'
#'
#'
#' @export


build_questionnaire <- function(i, ans) {
  if (ans == "AUDIT_part1" ) {
    inputId <- as.character(i)
    label <- AUDIT$Question[i]
    choices <- as.character(AUDIT[i, 2:6])
    shiny::radioButtons(inputId = inputId, label = label,
                 choices = choices, selected=character(0), choiceValues=c(0,1,2,3,4))
  }
  else if (ans == "AUDIT_part2") {
    inputId <- as.character(i)
    label <- AUDIT$Question[i]
    choices <- as.character(AUDIT[i, 2:4])
    shiny::radioButtons(inputId = inputId, label = label,
                 choices = choices, selected=character(0), choiceValues=c(0,2,4))
  }
  else if (ans == "DASS") {
    inputId <- as.character(i)
    label <- DASS$Question[i]
    choices <- as.character(DASS[i, 2:5])
    shiny::radioButtons(inputId = inputId, label = label,
                        choices = choices, selected=character(0), choiceValues=c(0,1,2,3))
  }
}

