#################################################################
##                 Stroop Preprocessing Script                 ##
##            Date: Jan 17, 2023 - Final Version               ##
#################################################################

# loading packages
#library(tidyverse)


#' @title Merges separate data files into one
#' @description
#'  Takes all separate participant raw data .csv files and merges them into
#' one pre-processed file  containing the important Stroop deadline task measures
#' (i.e., accuracy and response time)
#'
#' @param datawd The absolute filepath of your data folder containing raw participant data files.
#'               Make sure you use a character string (e.g., "C:/...")
#' @returns A data frame of all merged and pre-processed raw Stroop Task data.
#'         Specifically, practice trials accuracy, test trials accuracy,
#'         proportion of no responses, and adaptive response window, for each subject.
#' @details Use on data generated by JsPsych Stroop Deadline experiment.
#'
#' @note Takes all .csv files from the data folder, even if some files do not contain all data
#'          (e.g., participant did not finish the entire task). Only works on .csv type files.
#'
#' @examples
#' data_folder <- getwd()
#' merge_data_files(data_folder)
#'
#'
#' @export
merge_data_files <- function(datawd) {

# read in csv files from stroop data folder
file_names <-list.files(datawd, pattern="*.csv", full.names = TRUE)

# merge files
data_stroop <<- lapply(file_names, read.csv)

# create final data frame
stroop_metrics <<- matrix(NA, nrow = length(file_names), ncol = 1)
stroop_metrics <<- as.data.frame(stroop_metrics)

##-------------------------
##  Add Subject ID column
##-------------------------

colnames(stroop_metrics)[1] <<-  "uniqueSubID"

for (subj in 1:length(file_names)) {

  # add ID column
  stroop_metrics[subj,1] <<-  data_stroop[[subj]]$uniqueSubID[1]

}

##------------------------
##  Add Accuracy and RT Metrics
##------------------------

for (subj in 1:nrow(stroop_metrics)) {

  ## proportions of correct responses in practice phase
  pract_acc <- data_stroop[[subj]] %>%
    dplyr::filter(test_part != "test" & test_part != "" )
  stroop_metrics[subj,"pract_acc"] <<- sum(pract_acc$correct == "true") / length(pract_acc$correct)

  ## proportions of correct responses & No responses in test phase
  test_acc <- data_stroop[[subj]] %>%
    dplyr::filter(test_part == "test")
  stroop_metrics[subj,"test_acc"] <<-sum(test_acc$correct == "true") / length(test_acc$correct)
  stroop_metrics[subj,"no_resp_prop"] <<-sum(test_acc$correct == "no_response") / length(test_acc$correct)

  ## adaptive response window in last block
  adapt_win <- data_stroop[[subj]] %>%
    dplyr::filter(test_part == "test")
  stroop_metrics[subj,"adaptive_response_window"] <<- tail(adapt_win$adaptive_window, n=1)
}
}

##----------------------------------------------------------------
##                        Data Exportation                       -
##----------------------------------------------------------------

#' @title Saves the previously merged data file
#' @description
#'  Saves the pre-processed and merged Stroop deadline .csv data file into
#'  a specified directory, under a chosen file name.
#'
#' @param wd The absolute filepath of the folder in which you want the file to be saved.
#'               Make sure you use a character string (e.g., "C:/...")
#' @param file_name Default: "stroop_data". The name of the saved file in character string
#' @returns A .csv file saved in specified directory.
#' @details Use on data generated by JsPsych Stroop Deadline experiment.
#'
#' @note Requires your dataframe to already be in your Environment.
#' You can run merge_data_files() if you do not have your dataframe ready.
#'
#' @examples
#' data_folder <- getwd()
#' merge_data_files(data_folder)
#' save_data(data_folder, "my_data")
#'
#'
#'
#' @export
save_data <- function (wd, file_name="stroop_data") {
setwd(wd)
  file_name <- paste(file_name, ".csv", sep="")
# export as file
write.csv(stroop_metrics, file = file_name)
}

