

#' @title Merges Your Score into General Population Data
#' @description
#'  Takes your raw data .csv files and merges them into
#' one general population data file  containing all the important measures
#'
#'
#' @param datawd The absolute filepath of your data folder containing general population data file.
#'               Make sure you use a character string (e.g., "C:/...")
#' @param filename The file name of your data file that you want merged.
#'               Make sure you use a character string
#' @returns A data frame of all merged and pre-processed data.
#'
#' @details Use on data generated by ProjectExplicit experiment.
#'
#' @note Takes all .csv files from the data folder, even if some files do not contain all data
#'          (e.g., participant did not finish the entire task). Only works on .csv type files.
#'
#' @examples
#' data_folder <- getwd()
#' filename <- "audit_outcome.csv"
#' merge_data_files(data_folder, filename)
#'
#'
#' @export
merge_data_files <- function(filename) {

# read in csv files from data folder
  package_directory <- system.file(package = "ProjectExplicit")
general_data <- read.csv(paste(package_directory, "/general_data.csv", sep=""))
your_data <- read.csv(paste(package_directory, "/userdata/", filename, sep=""))

#change column names of your data
if (filename == "audit_outcome.csv") {
  your_outcome <- data.frame(sum(as.numeric(your_data[[2]])))
  colnames(your_outcome) <- "AUDIT"
}
if (filename == "dass_outcome.csv") {
  your_outcome <- sum(as.numeric(your_data[[2]]))
  colnames(your_outcome) <- "DASS"
}
if (filename == "sdl_outcome.csv") {
  your_outcome <- tail(your_data$adaptive_window[!is.na(your_data$adaptive_window)], 1)
  colnames(your_outcome) <- "SDL_Score"
} else {
  warning("Unrecognized data file name.
          Please check whether your specified data exists")
}

#merge files
general_data <- general_data %>%
  full_join(your_outcome)
return(general_data)
}

##----------------------------------------------------------------
##                        Data Exportation                       -
##----------------------------------------------------------------

#' @title Saves the previously merged data file
#' @description
#'  Saves the pre-processed and merged Stroop deadline .csv data file into
#'  a specified directory, under a chosen file name.
#'
#' @param wd The absolute filepath of the folder in which you want the file to be saved.
#'               Make sure you use a character string (e.g., "C:/...")
#' @param file_name Default: "stroop_data". The name of the saved file in character string
#' @returns A .csv file saved in specified directory.
#' @details Use on data generated by JsPsych Stroop Deadline experiment.
#'
#' @note Requires your dataframe to already be in your Environment.
#' You can run merge_data_files() if you do not have your dataframe ready.
#'
#' @examples
#' data_folder <- getwd()
#' merge_data_files(data_folder)
#' save_data(data_folder, "my_data")
#'
#'
#'
#' @export
save_data <- function (wd, filename="general_data.csv") {
setwd(wd)
# export as file
write.csv(general_data, file = filename)
}

